---
title: "DS2 Midterm"
author: "Mufeng Xu"
date: "3/28/2021"
output: html_document
---

```{r}
library(tidyverse)
library(patchwork)
library(ggcorrplot)
library(ISLR)
library(caret)
library(randomForest)
library(MASS)
library(pROC)
library(AppliedPredictiveModeling)
```

```{r}
# Load and tidy
stroke_df = read_csv("healthcare-dataset-stroke-data.csv") %>% 
  dplyr::select(gender:stroke) %>% 
  filter(!bmi == "N/A") %>% 
  na.omit() %>% 
  janitor::clean_names() %>% 
  mutate(
    gender = case_when(gender == "Male" ~ 0,
                       gender == "Female" ~ 1,
                       gender == "Other" ~ 2),
    ever_married = case_when(ever_married == "No" ~ 0,
                             ever_married == "Yes" ~ 1),
    work_type = case_when(work_type == "children" ~ 0,
                          work_type == "Govt_job" ~ 1,
                          work_type == "Never_worked" ~ 2,
                          work_type == "Private" ~ 3,
                          work_type == "Self-employed" ~ 4),
    residence_type = case_when(residence_type == "Rural" ~ 0,
                               residence_type == "Urban" ~ 1),
    smoking_status = case_when(smoking_status == "formerly smoked" ~ 0,
                               smoking_status == "never smoked" ~ 1,
                               smoking_status == "smokes" ~ 2,
                               smoking_status == "Unknown" ~ 3)
  ) %>% 
  mutate(bmi = as.numeric(bmi),
         stroke = as.factor(stroke))

summary(stroke_df)
```

# EDA
```{r}
# Correlation Matrix
model.matrix(~0+., data = stroke_df) %>% 
  cor(use = "pairwise.complete.obs") %>% 
  ggcorrplot(show.diag = F, type = "lower", 
             lab = TRUE, lab_size = 2, 
             title = "Correlation of parameters of interest")

# scatter plots between variables
pairs(stroke_df) # pairs plot

featurePlot(x = stroke_df[, 1:10], 
            y = stroke_df$stroke,
            scales = list(x = list(relation = "free"), 
                          y = list(relation = "free")),
            plot = "density",
            pch = "|", 
            auto.key = list(columns = 2),
            font = 2) # density plot

stroke_plot = stroke_df %>% 
  filter(stroke == 1) %>% 
  keep(is.numeric) %>% 
  gather() %>% 
  ggplot(aes(value)) + 
  facet_wrap(~ key, scales = "free") +
  geom_histogram()

nonstroke_plot = stroke_df %>% 
  filter(stroke == 0) %>% 
  keep(is.numeric) %>% 
  gather() %>% 
  ggplot(aes(value)) + 
  facet_wrap(~ key, scales = "free") +
  geom_histogram()

stroke_plot + nonstroke_plot
```

# Models

```{r}
# split train vs. test
stroke_df = stroke_df %>% 
  mutate(gender = as.factor(gender),
         hypertension = as.factor(hypertension),
         heart_disease = as.factor(heart_disease),
         ever_married = as.factor(ever_married),
         work_type = as.factor(work_type),
         residence_type = as.factor(residence_type),
         smoking_status = as.factor(smoking_status),
         stroke = as.factor(stroke)) %>% 
  mutate(id = 1:nrow(stroke_df))

set.seed(2)
sample_size = floor(0.8 * nrow(stroke_df))
train = sample_n(stroke_df, size = sample_size)
test = anti_join(stroke_df, train, by = "id") %>% dplyr::select(gender:stroke)
train = train %>% dplyr::select(gender:stroke)
stroke_df = stroke_df %>% dplyr::select(gender:stroke)
```


## GLM
```{r}
glm_fit = glm(stroke ~., data = train, family = binomial)
summary(glm_fit)

step_glm_fit = stepAIC(glm_fit, direction = "both", trace = FALSE)
summary(step_glm_fit)

anova(glm)

# Confusion Matrix
prob = predict(step_glm_fit, newdata = test, type = "response")
pred = rep("0", length(prob))
pred[prob > 0.5] = "1"
confusionMatrix(data = as.factor(pred), reference = test$stroke, positive = "1")

# ROC
glm_prob2 = predict(glm_fit, newdata = test, type = "response")
roc = roc(test$stroke, glm_prob2)
plot(roc, legacy.axes = TRUE, print.auc = TRUE)
plot(smooth(roc), col = 4, add = TRUE)
```

## LDA

```{r}
lda_fit = lda(stroke ~ age + hypertension + heart_disease + avg_glucose_level, data = train)
lda_pred = predict(lda_fit, newdata = test)
roc_lda = roc(test$stroke, lda_pred$posterior[,2], levels = c("0", "1"))
plot(roc_lda, legacy.axes = TRUE, print.auc = TRUE)
plot(smooth(roc_lda), col = 4, add = TRUE)
```

## QDA

```{r}
qda_fit = qda(stroke ~ age + hypertension + heart_disease + avg_glucose_level, data = train)
qda_pred = predict(qda_fit, newdata = test)
roc_qda = roc(test$stroke, qda_pred$posterior[,2], levels = c("0", "1"))
plot(roc_qda, legacy.axes = TRUE, print.auc = TRUE)
plot(smooth(roc_qda), col = 4, add = TRUE)
```

## RandomForest

```{r}
rfGrid = data.frame(
  .mtry = c(2,3,5,6),
  .splitrule = "gini",
  .min.node.size = 5
)

ctrl1 = trainControl(
    method = "oob",
    number = 5,
    verboseIter = TRUE
)

rf_model = train(
    stroke ~ .,
    train,
    method = "ranger",
    tuneLength = 3,
    tuneGrid = rfGrid,
    trControl = ctrl1
)

x_test = test %>% dplyr::select(-stroke)

rf_pred = predict(rf_model, newdata = x_test) 

confusionMatrix(rf_pred, factor(test[["stroke"]]), positive = "1")

```

